
###
POST {{BASE_URL}}/auth/login
Content-Type: application/json

{
  "email": "test1@gmail.com",
  "password": "password"
}

###


POST {{BASE_URL}}/auth/register
Content-Type: application/json

{
  "firstName": "Kishor",
  "lastName": "Mainali",
  "email": "test2@gmail.com",
  "password": "password",
  "phoneNumber": "9860086143"
}

###

POST {{BASE_URL}}/auth/refresh-token
Content-Type: application/json
x-refresh-token: {{REFRESH_TOKEN}}

###


GET {{BASE_URL}}/v1/products
Content-Type: application/json
Authorization: Bearer {{ACCESS_TOKEN}}

###


GET {{BASE_URL}}/v1/banners
Content-Type: application/json
Authorization: Bearer {{ACCESS_TOKEN}}

###

